const actionTypes = {
  GET_DATA_START: "GET_DATA_START",
  GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
  GET_DATA_FAILURE: "GET_DATA_FAILURE",
  GET_DATA_START_CATEGORY: "GET_DATA_START_CATEGORY",
  GET_DATA_SUCCESS_CATEGORY: "GET_DATA_SUCCESS_CATEGORY",
  GET_DATA_FAILURE_CATEGORY: "GET_DATA_FAILURE_CATEGORY",
  GET_DATA_START_CATEGORY_LIST: "GET_DATA_START_CATEGORY_LIST",
  GET_DATA_SUCCESS_CATEGORY_LIST: "GET_DATA_SUCCESS_CATEGORY_LIST",
  GET_DATA_FAILURE_CATEGORY_LIST: "GET_DATA_FAILURE_CATEGORY_LIST",
  ADD_TO_BASKET: "ADD_TO_BASKET",
  REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
  UPDATE_AMOUNT: "UPDATE_AMOUNT",
};
export default actionTypes;
